/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package optimusnet;

/**
 *
 * @author marie
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        //Al iniciar se apagaran estos componentes para probar pero siempre deben estar encendidos al iniciar programa
         btnModificar.setVisible(true);
         btnMostrarTablaRuteo.setVisible(true);
         btnInformacion.setVisible(true);
         lblVerResultados3.setVisible(true);
         
         // Estos hay que tenerlos apagados en el inicio de programa. Estos hay que encenderlos luego...
         sliderMetrica2.setVisible(false);
         sliderMetrica1.setVisible(false);
         sliderAD1.setVisible(false);
         btnGuardar.setVisible(false);
         btnCambiarIp.setVisible(false);
         btnCancelar.setVisible(false);
         lblVerResultados3.setVisible(false);
         lbl1.setVisible(false);
         lbl2.setVisible(false);
         lbl3.setVisible(false);
         lbl4.setVisible(false);
         lblPracticar1.setVisible(false);
         lblPracticar2.setVisible(false);
         lblPracticar3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        R5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPracticar = new javax.swing.JLabel();
        lblVerResultados3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnInformacion = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        slash = new javax.swing.JLabel();
        slash1 = new javax.swing.JLabel();
        slash2 = new javax.swing.JLabel();
        slash3 = new javax.swing.JLabel();
        slash4 = new javax.swing.JLabel();
        slash5 = new javax.swing.JLabel();
        lblVerResultados1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblPracticar2 = new javax.swing.JLabel();
        sliderMetrica1 = new javax.swing.JSlider();
        sliderMetrica2 = new javax.swing.JSlider();
        sliderAD1 = new javax.swing.JSlider();
        btnCambiarIp = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        lblAD1 = new javax.swing.JLabel();
        lblMetrica2 = new javax.swing.JLabel();
        lblMetrica1 = new javax.swing.JLabel();
        lblPracticar3 = new javax.swing.JLabel();
        lblPracticar1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        btnMostrarTablaRuteo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 720));
        getContentPane().setLayout(null);

        R1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/network-router-icon-1 (1).png"))); // NOI18N
        getContentPane().add(R1);
        R1.setBounds(60, 120, 50, 40);

        R2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/network-router-icon-1 (1).png"))); // NOI18N
        getContentPane().add(R2);
        R2.setBounds(400, 120, 50, 40);

        R3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/network-router-icon-1 (1).png"))); // NOI18N
        getContentPane().add(R3);
        R3.setBounds(400, 380, 50, 38);

        R4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/network-router-icon-1 (1).png"))); // NOI18N
        getContentPane().add(R4);
        R4.setBounds(250, 570, 50, 38);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/switches-icon-26 (1).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 250, 60, 40);

        R5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/network-router-icon-1 (1).png"))); // NOI18N
        getContentPane().add(R5);
        R5.setBounds(70, 380, 50, 38);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/datos.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 80, 35, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/configuraciones 1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(730, 250, 40, 35);

        lblPracticar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPracticar.setForeground(new java.awt.Color(5, 71, 100));
        lblPracticar.setText("Practicar");
        lblPracticar.setIconTextGap(1);
        getContentPane().add(lblPracticar);
        lblPracticar.setBounds(770, 250, 160, 30);

        lblVerResultados3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVerResultados3.setForeground(new java.awt.Color(5, 71, 100));
        lblVerResultados3.setText("para elegir la mejor ruta");
        lblVerResultados3.setIconTextGap(1);
        getContentPane().add(lblVerResultados3);
        lblVerResultados3.setBounds(770, 110, 210, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(660, 70, 10, 610);

        jLabel12.setText("10.0.0.3");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 250, 50, 16);

        jLabel15.setText("10.0.0.1");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 100, 50, 16);

        jLabel16.setText("10.0.0.0");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(9, 250, 50, 16);

        jLabel17.setText("10.0.0.4");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(240, 410, 50, 16);

        jLabel18.setText("10.0.0.2");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(229, 200, 50, 16);

        jLabel20.setText("10.0.0.6");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(80, 480, 50, 16);

        btnInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/informacion.png"))); // NOI18N
        getContentPane().add(btnInformacion);
        btnInformacion.setBounds(1240, 30, 64, 64);

        jLabel19.setText("10.0.0.5");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(360, 490, 50, 16);

        jLabel22.setText("29");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(500, 250, 30, 16);

        jLabel23.setText("29");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(280, 100, 20, 16);

        jLabel24.setText("29");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(300, 410, 20, 16);

        jLabel25.setText("28");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(290, 200, 20, 16);

        jLabel26.setText("29");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(420, 490, 20, 16);

        jLabel27.setText("29");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(140, 480, 20, 16);

        jLabel28.setText("29");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(70, 250, 20, 16);

        jLabel29.setText("/");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(410, 490, 10, 16);

        slash.setText("/");
        getContentPane().add(slash);
        slash.setBounds(280, 200, 43, 16);

        slash1.setText("/");
        getContentPane().add(slash1);
        slash1.setBounds(290, 410, 10, 16);

        slash2.setText("/");
        getContentPane().add(slash2);
        slash2.setBounds(490, 250, 10, 16);

        slash3.setText("/");
        getContentPane().add(slash3);
        slash3.setBounds(270, 100, 10, 16);

        slash4.setText("/");
        getContentPane().add(slash4);
        slash4.setBounds(60, 250, 43, 16);

        slash5.setText("/");
        getContentPane().add(slash5);
        slash5.setBounds(130, 480, 10, 16);

        lblVerResultados1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVerResultados1.setForeground(new java.awt.Color(5, 71, 100));
        lblVerResultados1.setText("Ver resultados");
        lblVerResultados1.setIconTextGap(1);
        getContentPane().add(lblVerResultados1);
        lblVerResultados1.setBounds(770, 80, 190, 30);

        lbl1.setText("1. Longest Prefix Match");
        getContentPane().add(lbl1);
        lbl1.setBounds(750, 150, 160, 16);

        lbl2.setText("2. Distancia administrativa  ");
        getContentPane().add(lbl2);
        lbl2.setBounds(750, 170, 170, 16);

        lbl3.setText("3. Metrica ");
        getContentPane().add(lbl3);
        lbl3.setBounds(750, 190, 140, 16);

        lbl4.setText("4. Balanceo");
        getContentPane().add(lbl4);
        lbl4.setBounds(750, 210, 140, 16);

        lblPracticar2.setText("Métrica #2");
        getContentPane().add(lblPracticar2);
        lblPracticar2.setBounds(760, 390, 90, 16);
        getContentPane().add(sliderMetrica1);
        sliderMetrica1.setBounds(760, 340, 200, 26);
        getContentPane().add(sliderMetrica2);
        sliderMetrica2.setBounds(760, 420, 200, 26);
        getContentPane().add(sliderAD1);
        sliderAD1.setBounds(760, 490, 200, 26);

        btnCambiarIp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/Frame 8.png"))); // NOI18N
        getContentPane().add(btnCambiarIp);
        btnCambiarIp.setBounds(710, 550, 380, 39);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/Frame 7.png"))); // NOI18N
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(920, 610, 161, 34);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/Frame 5 (1).png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(720, 610, 160, 34);

        lblAD1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAD1.setForeground(new java.awt.Color(153, 0, 204));
        lblAD1.setText("5");
        getContentPane().add(lblAD1);
        lblAD1.setBounds(260, 140, 10, 16);

        lblMetrica2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetrica2.setForeground(new java.awt.Color(255, 51, 51));
        lblMetrica2.setText("10");
        getContentPane().add(lblMetrica2);
        lblMetrica2.setBounds(100, 250, 14, 16);

        lblMetrica1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetrica1.setForeground(new java.awt.Color(255, 51, 51));
        lblMetrica1.setText("110");
        getContentPane().add(lblMetrica1);
        lblMetrica1.setBounds(390, 250, 43, 16);

        lblPracticar3.setText("Distancia administrativa #1");
        getContentPane().add(lblPracticar3);
        lblPracticar3.setBounds(760, 460, 160, 16);

        lblPracticar1.setText("Métrica #1");
        getContentPane().add(lblPracticar1);
        lblPracticar1.setBounds(760, 310, 90, 16);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/Frame 5.png"))); // NOI18N
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(760, 300, 270, 34);

        btnMostrarTablaRuteo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/Frame 6.png"))); // NOI18N
        btnMostrarTablaRuteo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTablaRuteoMouseClicked(evt);
            }
        });
        getContentPane().add(btnMostrarTablaRuteo);
        btnMostrarTablaRuteo.setBounds(760, 140, 267, 34);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimusnet/img/Pantalla principal (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1410, 705);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarTablaRuteoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTablaRuteoMouseClicked
      //Mostrar tabla de ruteo
      tablaRuteoGUI tablaRuteo = new tablaRuteoGUI(this, true);
      tablaRuteo.setVisible(true);
    }//GEN-LAST:event_btnMostrarTablaRuteoMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // Desactivamos...
         btnModificar.setVisible(false);
         btnMostrarTablaRuteo.setVisible(false);
         btnInformacion.setVisible(false);
         lblVerResultados3.setVisible(false);
        // Activamos...
         sliderMetrica2.setVisible(true);
         sliderMetrica1.setVisible(true);
         sliderAD1.setVisible(true);
         btnGuardar.setVisible(true);
         btnCambiarIp.setVisible(true);
         btnCancelar.setVisible(true);
         lblVerResultados3.setVisible(true);
         lbl1.setVisible(true);
         lbl2.setVisible(true);
         lbl3.setVisible(true);
         lbl4.setVisible(true);
         lblPracticar1.setVisible(true);
         lblPracticar2.setVisible(true);
         lblPracticar3.setVisible(true);
         
         //Modificamos texto "ver Resultados" por Métodos
         lblVerResultados1.setText("Métodos");
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // activamos
         btnModificar.setVisible(true);
         btnMostrarTablaRuteo.setVisible(true);
         btnInformacion.setVisible(true);
         lblVerResultados3.setVisible(true);
         
         // descativamos
         sliderMetrica2.setVisible(false);
         sliderMetrica1.setVisible(false);
         sliderAD1.setVisible(false);
         btnGuardar.setVisible(false);
         btnCambiarIp.setVisible(false);
         btnCancelar.setVisible(false);
         lblVerResultados3.setVisible(false);
         lbl1.setVisible(false);
         lbl2.setVisible(false);
         lbl3.setVisible(false);
         lbl4.setVisible(false);
         lblPracticar1.setVisible(false);
         lblPracticar2.setVisible(false);
         lblPracticar3.setVisible(false);         
        //Modificamos texto Métodos por "ver Resultados"
         lblVerResultados1.setText("Ver resultados");
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // activamos
         btnModificar.setVisible(true);
         btnMostrarTablaRuteo.setVisible(true);
         btnInformacion.setVisible(true);
         lblVerResultados3.setVisible(true);
         
         // descativamos
         sliderMetrica2.setVisible(false);
         sliderMetrica1.setVisible(false);
         sliderAD1.setVisible(false);
         btnGuardar.setVisible(false);
         btnCambiarIp.setVisible(false);
         btnCancelar.setVisible(false);
         lblVerResultados3.setVisible(false);
         lbl1.setVisible(false);
         lbl2.setVisible(false);
         lbl3.setVisible(false);
         lbl4.setVisible(false);
         lblPracticar1.setVisible(false);
         lblPracticar2.setVisible(false);
         lblPracticar3.setVisible(false);         
        //Modificamos texto Métodos por "ver Resultados"
         lblVerResultados1.setText("Ver resultados");
    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel R3;
    private javax.swing.JLabel R4;
    private javax.swing.JLabel R5;
    private javax.swing.JLabel btnCambiarIp;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnInformacion;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnMostrarTablaRuteo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblAD1;
    private javax.swing.JLabel lblMetrica1;
    private javax.swing.JLabel lblMetrica2;
    private javax.swing.JLabel lblPracticar;
    private javax.swing.JLabel lblPracticar1;
    private javax.swing.JLabel lblPracticar2;
    private javax.swing.JLabel lblPracticar3;
    private javax.swing.JLabel lblVerResultados1;
    private javax.swing.JLabel lblVerResultados3;
    private javax.swing.JLabel slash;
    private javax.swing.JLabel slash1;
    private javax.swing.JLabel slash2;
    private javax.swing.JLabel slash3;
    private javax.swing.JLabel slash4;
    private javax.swing.JLabel slash5;
    private javax.swing.JSlider sliderAD1;
    private javax.swing.JSlider sliderMetrica1;
    private javax.swing.JSlider sliderMetrica2;
    // End of variables declaration//GEN-END:variables
}
